Repository be15-4th-b612-DayOfLittlePrince/be15-4th-b612-DayOfTheLittlePrince, pull requests merged in 2025-05, with the labels that each got.

#28 Dlp 22 fe 투두 리스트 조회 뷰 구현
  be14-4th-b612-littleprince-fe/src/assets/icons/edit.png
  be14-4th-b612-littleprince-fe/src/assets/icons/note.png
  be14-4th-b612-littleprince-fe/src/features/calendar/router.js
  be14-4th-b612-littleprince-fe/src/features/calendar/views/PlanListView.vue
  be14-4th-b612-littleprince-fe/tailwind.config.js
Labels: feat

#30 feat: 회원 가입 페이지 구현
  be14-4th-b612-littleprince-fe/src/features/user/views/SignupView.vue
Labels: feat

#33 Dlp 26 fe 단기 리스트 조회 및 수정 뷰 구현
  be14-4th-b612-littleprince-fe/src/features/calendar/router.js
  be14-4th-b612-littleprince-fe/src/features/calendar/views/PlanListView.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/views/ShortTermListView.vue
Labels: feat

#37 Dlp 29 fe 장기 리스트 조회 뷰 구현
  be14-4th-b612-littleprince-fe/src/features/calendar/router.js
  be14-4th-b612-littleprince-fe/src/features/calendar/views/LongTermListView.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/views/PlanListView.vue
Labels: feat

#40 Dlp 28 fe 메인페이지 로딩화면 수정
  be14-4th-b612-littleprince-fe/public/audio/background.mp3
  be14-4th-b612-littleprince-fe/src/App.vue
  be14-4th-b612-littleprince-fe/src/assets/icons/bgm-off.png
  be14-4th-b612-littleprince-fe/src/assets/icons/bgm-on.png
  be14-4th-b612-littleprince-fe/src/components/common/BgmPlayer.vue
  be14-4th-b612-littleprince-fe/src/components/common/LoadingSpinner.vue
  be14-4th-b612-littleprince-fe/src/components/common/Spinner.vue
  be14-4th-b612-littleprince-fe/src/features/main/components/PlanetScene.vue
Labels: bug

#42 Dlp 19 be 로그인 api 구현
  be15-4th-b612-littleprince-be/build.gradle
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/command/dto/response/TokenResponse.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/query/controller/AuthQueryController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/query/dto/request/LoginRequest.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/query/service/AuthQueryService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/query/service/AuthQueryServiceImpl.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/common/exception/UnAuthorizationException.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/RedisConfig.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/SecurityConfig.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/security/CustomAccessDeniedHandler.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/security/CustomAuthenticationEntryPoint.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/security/JwtAuthenticationFilter.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/security/model/CustomUserDetail.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/infra/redis/RefreshTokenRepository.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/infra/redis/RefreshTokenRepositoryImpl.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/query/dto/FindMemberDTO.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/utils/jwt/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/utils/jwt/JwtErrorResponse.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/utils/jwt/JwtTokenProvider.java
  be15-4th-b612-littleprince-be/src/main/resources/application.yml
  be15-4th-b612-littleprince-be/src/main/resources/mappers/member/MemberQueryMapper.xml
  be15-4th-b612-littleprince-be/src/test/java/littleprince/auth/fixture/LoginRequestFixture.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/auth/query/service/AuthQueryServiceImplTest.java
Labels: feat

#43 DLP-27-fe-플랜 등록 페이지 컴포넌트 크기 수정
  be14-4th-b612-littleprince-fe/src/features/calendar/components/TodoList.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/views/PlanWriteForm.vue
Labels: fix

#52 fix: 회원가입 CSS 수정
  be14-4th-b612-littleprince-fe/src/features/user/views/SignupView.vue
Labels: feat

#54 fix: 회원 CSS 수정 #53
  be14-4th-b612-littleprince-fe/src/assets/styles/auth-container.css
  be14-4th-b612-littleprince-fe/src/features/user/components/MainLogo.vue
  be14-4th-b612-littleprince-fe/src/features/user/views/LoginView.vue
  be14-4th-b612-littleprince-fe/src/features/user/views/SignupView.vue
Labels: feat

#61 Dlp 38 fe ai 생성하기 컴포넌트 구현
  be14-4th-b612-littleprince-fe/src/features/calendar/components/AISuggestionModal.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/components/TodoList.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/views/LongTermListView.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/views/PlanWriteForm.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/views/ShortTermListView.vue
Labels: feat

#65 Dlp 42 fe UI 버튼 수정
  be14-4th-b612-littleprince-fe/src/features/calendar/components/TodoList.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/views/LongTermListView.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/views/ShortTermListView.vue
Labels: fix

#59 Dlp 31 be 로그아웃 api 구현
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/command/controller/AuthCommandController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/command/service/AuthCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/command/service/AuthCommandServiceImpl.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/common/exception/GlobalExceptionHandler.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/SecurityConfig.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/auth/command/service/AuthCommandServiceImplTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/auth/fixture/LogoutRequest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/auth/fixture/LogoutRequestFixture.java
Labels: feat

#66 Dlp 39 be 단기 리스트 조회 구현
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/SecurityConfig.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/query/controller/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/aggregate/domain/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/controller/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/dto/request/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/dto/response/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/mapper/ShortListCommandMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/exception/PlanErrorCode.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/controller/PlanQueryController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/ShortListDTO.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/request/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/response/ShortListResponse.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/mapper/ShortListQueryMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/service/ShortListQueryService.java
  be15-4th-b612-littleprince-be/src/main/resources/mappers/plan/ShortListQueryMapper.xml
Labels: feat

#68 fix: 매퍼 수정
  be15-4th-b612-littleprince-be/src/main/resources/mappers/plan/ShortListQueryMapper.xml
Labels: fix

#85 Dlp 47 be 장기 투두 리스트 상세 조회
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/SecurityConfig.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/aggregate/domain/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/domain/aggregate/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/controller/LongListQueryController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/response/LongDetailDTO.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/response/LongDetailResponse.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/mapper/LongListQueryMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/service/LongListQueryService.java
  be15-4th-b612-littleprince-be/src/main/resources/mappers/plan/LongListQueryMapper.xml
Labels: feat

#90 Dlp 58 be 장기 플랜 응답 값 수정
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/response/LongDetailDTO.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/response/LongListDTO.java
  be15-4th-b612-littleprince-be/src/main/resources/mappers/plan/LongListQueryMapper.xml
Labels: fix

#103 fix: 멤버 엔티티 생성
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/repository/MemberRepository.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/domain/aggregate/Member.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/query/controller/MemberQueryController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/query/service/MemberQueryService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/query/service/MemberQueryServiceImpl.java
Labels: fix

#106 Dlp 44 be 단기 투두 리스트 생성 구현
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/SecurityConfig.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/controller/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/controller/ShortTodoCommandController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/dto/request/CreateShortTodoRequestDto.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/dto/request/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/domain/aggregate/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/domain/aggregate/Task.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/mapper/ShortListCommandMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/mapper/ShortTodoCommandMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/repository/TaskRepository.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/service/ShortTodoCommandService.java
Labels: feat

#107 Dlp 66 be 장기 플랜 전체 조회
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/SecurityConfig.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/controller/LongListQueryController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/response/LongPlanDTO.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/response/LongPlanResponse.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/mapper/LongListQueryMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/service/LongListQueryService.java
  be15-4th-b612-littleprince-be/src/main/resources/mappers/plan/LongListQueryMapper.xml
Labels: feat

#109 chore: 스웨거 설정 추가 #108
  be15-4th-b612-littleprince-be/build.gradle
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/SecurityConfig.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/SwaggerConfig.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/controller/MemberCommandController.java
  be15-4th-b612-littleprince-be/src/main/resources/application.yml
Labels: feat

#110 Dlp 67 be 단기 플랜 여부 조회
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/controller/ShortListQueryController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/response/ShortPlanDateDTO.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/response/ShortPlanDateResponse.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/mapper/ShortListQueryMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/service/ShortListQueryService.java
  be15-4th-b612-littleprince-be/src/main/resources/mappers/plan/ShortListQueryMapper.xml
Labels: feat

#115 Dlp 65 be 사용자 아이템 숨김 처리, 아이템 추가 기능 구현
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/Exception/ItemErrorCode.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/application/controller/ItemCommandController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/application/dto/request/Exp.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/application/dto/response/Exp.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/application/service/ItemCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/domain/GetItemId.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/domain/aggregate/GetItem.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/domain/aggregate/Item.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/domain/repository/GetItemRepository.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/domain/repository/ItemRepository.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/domain/repository/dummy
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/query/dto/GetItemDTO.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/query/mapper/ItemMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/exception/MemberErrorCode.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/query/dto/response/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/query/dto/response/MemberInfoResponse.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/query/mapper/MemberQueryMapper.java
  be15-4th-b612-littleprince-be/src/main/resources/mappers/item/ItemMapper.xml
  be15-4th-b612-littleprince-be/src/main/resources/mappers/member/MemberQueryMapper.xml
Labels: feat

#123 Dlp 60 be 회고 등록 구현
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/application/controller/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/application/controller/ReviewCommandController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/application/dto/request/CreateReviewRequest.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/application/dto/request/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/application/dto/response/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/application/service/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/application/service/ReviewCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/domain/aggregate/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/domain/aggregate/Review.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/domain/repository/Exam.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/domain/repository/JpaReviewRepository.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/exception/ReviewErrorCode.java
Labels: feat

#128 Dlp 73 be 회원가입 로직 수정
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/application/controller/ItemCommandController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/application/service/BadgeCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/application/service/BadgeCommandServiceImpl.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/application/service/ItemCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/query/mapper/GetBadgeCommandMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/controller/MemberCommandController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/dto/constant/MemberLevel.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/service/MemberCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/service/MemberCommandServiceImpl.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/query/controller/MemberQueryController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/query/service/MemberQueryService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/query/service/MemberQueryServiceImpl.java
  be15-4th-b612-littleprince-be/src/main/resources/mappers/badge/GetBadgeCommandMapper.xml
Labels: fix

#129 feat: 회원가입, 로그인, 로그아웃 API 연결
  be14-4th-b612-littleprince-fe/package-lock.json
  be14-4th-b612-littleprince-fe/package.json
  be14-4th-b612-littleprince-fe/src/components/layout/SideBar.vue
  be14-4th-b612-littleprince-fe/src/features/user/api.js
  be14-4th-b612-littleprince-fe/src/features/user/components/MyPageModal.vue
  be14-4th-b612-littleprince-fe/src/features/user/views/LoginView.vue
  be14-4th-b612-littleprince-fe/src/features/user/views/SignupView.vue
  be14-4th-b612-littleprince-fe/src/main.js
  be14-4th-b612-littleprince-fe/src/plugins/axios.js
  be14-4th-b612-littleprince-fe/src/stores/auth.js
  be14-4th-b612-littleprince-fe/vite.config.js
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/SecurityConfig.java
Labels: feat

#130 Dlp 48 be 장기 프로젝트 생성 및 하위 투두 리스트 생성 구현
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/controller/LongTodoCommandController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/controller/ProjectTaskCommandController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/dto/request/CreateLongTodoRequestDto.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/dto/request/CreateProjectTaskRequestDto.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/service/LongTodoCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/service/ProjectTaskCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/domain/aggregate/Project.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/domain/aggregate/Task.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/repository/ProjectRepository.java
Labels: feat

#134 Dlp 71 be 장기 투두 체크 상태 토글 기능 구현
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/controller/ProjectTaskCommandController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/service/ProjectTaskCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/exception/PlanErrorCode.java
Labels: feat

#137 Dlp 51 be 장기 플랜 목록 삭제
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/controller/ProjectCommandController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/service/ProjectCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/exception/PlanErrorCode.java
Labels: feat

#138 Dlp 32 be 비밀번호 찾기 api 구현
  be14-4th-b612-littleprince-fe/src/features/user/api.js
  be14-4th-b612-littleprince-fe/src/features/user/router.js
  be14-4th-b612-littleprince-fe/src/features/user/views/ChangePasswordView.vue
  be14-4th-b612-littleprince-fe/src/features/user/views/FindPasswordView.vue
  be15-4th-b612-littleprince-be/build.gradle
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/command/controller/AuthCommandController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/command/dto/request/ChangePasswordRequest.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/command/service/AuthCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/command/service/AuthCommandServiceImpl.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/query/controller/AuthQueryController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/query/service/AuthQueryService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/auth/query/service/AuthQueryServiceImpl.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/common/exception/GlobalErrorCode.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/SecurityConfig.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/infra/redis/FindPasswordRepository.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/infra/redis/FindPasswordRepositoryImpl.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/annotation/ValidEmail.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/repository/MemberRepository.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/domain/aggregate/Member.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/exception/MemberErrorCode.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/utils/EmailUtils.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/utils/RandomStringUtils.java
  be15-4th-b612-littleprince-be/src/main/resources/application.yml
Labels: feat

#150 Dlp 87 fe 연동 api 생성
  be14-4th-b612-littleprince-fe/src/features/calendar/api.js
Labels: feat

#153 fix: AI 생성 버튼 오류 수정
  be14-4th-b612-littleprince-fe/src/features/calendar/views/ShortTermListView.vue
  be14-4th-b612-littleprince-fe/src/features/main/components/MainIconItem.vue
Labels: bug

#154 Dlp 82 be 행성 이름 수정 기능 구현
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/controller/MemberCommandController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/dto/request/PlanetNameRequest.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/service/MemberCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/service/MemberCommandServiceImpl.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/domain/aggregate/Member.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/exception/MemberErrorCode.java
Labels: feat

#158 Dlp 89 fe 행성 이름 수정 api 연동
  be14-4th-b612-littleprince-fe/src/components/common/PlanetScene.vue
  be14-4th-b612-littleprince-fe/src/features/main/api.js
  be14-4th-b612-littleprince-fe/src/features/main/components/MemberInfoItem.vue
Labels: feat

#162 Dlp 92 be 선택한 칭호 조회 기능 구현
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/query/controller/BadgeQueryController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/query/dto/BadgeDTO.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/query/dto/response/MyBadgeResponse.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/query/mapper/GetBadgeQueryMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/query/service/BadgeQueryService.java
  be15-4th-b612-littleprince-be/src/main/resources/mappers/badge/BadgeQueryMapper.xml
Labels: feat

#157 Dlp 79 fe 캘린더 api 연동
  be14-4th-b612-littleprince-fe/src/assets/styles/calendar-event.css
  be14-4th-b612-littleprince-fe/src/assets/styles/calendar.css
  be14-4th-b612-littleprince-fe/src/features/calendar/components/Calendar.vue
  be14-4th-b612-littleprince-fe/tailwind.config.js
Labels: feat

#172 Dlp 95 be 명언 조회 기능 구현
  be15-4th-b612-littleprince-be/src/main/java/littleprince/famousquotes/query/controller/FamousQuotesQueryController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/famousquotes/query/mapper/FamousQuotesMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/famousquotes/query/service/FamousQuotesQueryService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/famousquotes/query/service/FamousQuotesQueryServiceImpl.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/domain/aggregate/entity/FamousQuotes.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/query/mapper/ItemMapper.java
  be15-4th-b612-littleprince-be/src/main/resources/mappers/famousquotes/FamousQuotesMapper.xml
Labels: feat

#176 Dlp 84 fe 장기 체크 리스트 api 연동 및 프로젝트 제목 연결
  be14-4th-b612-littleprince-fe/src/features/calendar/views/LongTermListView.vue
Labels: feat, fix

#178 Dlp 81 fe ai 생성 모달 api 연동
  be14-4th-b612-littleprince-fe/src/features/calendar/api.js
  be14-4th-b612-littleprince-fe/src/features/calendar/components/AISuggestionModal.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/components/ShortTermList.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/components/TodoList.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/views/LongTermListView.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/views/PlanWriteForm.vue
Labels: feat

#175 Dlp 97 fe 플랜 등록 폼 응답 수정
  be14-4th-b612-littleprince-fe/src/features/calendar/views/PlanWriteForm.vue
Labels: fix

#181 feat: 명언 랜덤 조회 api 연동
  be14-4th-b612-littleprince-fe/src/assets/icons/shooting-star.png
  be14-4th-b612-littleprince-fe/src/components/layout/FamousQuotesModal.vue
  be14-4th-b612-littleprince-fe/src/features/main/api.js
  be14-4th-b612-littleprince-fe/src/features/user/views/LoginView.vue
Labels: feat

#183 Dlp 98 fe 메인페이지 캡쳐 구현
  be14-4th-b612-littleprince-fe/src/App.vue
  be14-4th-b612-littleprince-fe/src/components/layout/SideBar.vue
  be14-4th-b612-littleprince-fe/src/stores/ui.js
  be14-4th-b612-littleprince-fe/src/utils/setupThreeScene.js
Labels: feat

#187 Dlp 100 fe 레벨별 아이템 조회
  be14-4th-b612-littleprince-fe/src/App.vue
  be14-4th-b612-littleprince-fe/src/assets/data/SceneItems.js
  be14-4th-b612-littleprince-fe/src/components/layout/SideBar.vue
  be14-4th-b612-littleprince-fe/src/features/main/api.js
  be14-4th-b612-littleprince-fe/src/features/main/components/PlanetScene.vue
  be14-4th-b612-littleprince-fe/src/features/main/components/SceneItemManager.vue
  be14-4th-b612-littleprince-fe/src/features/user/components/MyPageModal.vue
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/application/dto/request/Exp.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/application/dto/response/Exp.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/domain/aggregate/entity/FamousQuotes.java
Labels: feat

#191 Dlp 103 fe 명언 모달 수정
  be14-4th-b612-littleprince-fe/src/App.vue
  be14-4th-b612-littleprince-fe/src/components/layout/FamousQuotesModal.vue
  be14-4th-b612-littleprince-fe/src/features/item/api.js
  be14-4th-b612-littleprince-fe/src/features/item/router.js
  be14-4th-b612-littleprince-fe/src/features/user/components/MyPageModal.vue
Labels: fix

#195 Dlp 105 fe 만렙 경험치 max 표시
  be14-4th-b612-littleprince-fe/src/features/main/components/MainIconItem.vue
  be14-4th-b612-littleprince-fe/src/features/main/components/MemberInfoItem.vue
  be14-4th-b612-littleprince-fe/src/features/main/components/PlanetScene.vue
  be14-4th-b612-littleprince-fe/src/features/user/components/MyPageModal.vue
  be14-4th-b612-littleprince-fe/src/features/user/views/SignupView.vue
Labels: fix

#203 Dlp 76 be 회원 탈퇴 api 구현
  be14-4th-b612-littleprince-fe/src/features/user/components/MyPageModal.vue
Labels: fix

#205 Dlp 108 fe 오늘의 할 일 api 연동
  be14-4th-b612-littleprince-fe/src/features/calendar/components/ShortTermList.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/components/TodoList.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/views/LongTermListView.vue
  be14-4th-b612-littleprince-fe/src/features/calendar/views/ShortTermListView.vue
  be14-4th-b612-littleprince-fe/src/features/main/components/MainIconItem.vue
Labels: feat

#209 Dlp 109 be 단기 플랜 전체 조회 api 구현
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/controller/ShortListQueryController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/response/ShortListsAllDTO.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/dto/response/ShortListsAllResponse.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/mapper/ShortListQueryMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/query/service/ShortListQueryService.java
  be15-4th-b612-littleprince-be/src/main/resources/mappers/plan/ShortListQueryMapper.xml
Labels: feat

#208 Dlp 112 be 테스트 코드 작성
  be15-4th-b612-littleprince-be/src/main/java/littleprince/item/command/domain/aggregate/entity/Item.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/domain/aggregate/Member.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/dto/request/CreateLongTodoRequestDto.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/dto/request/CreateProjectTaskRequestDto.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/application/dto/request/CreateShortTodoRequestDto.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/domain/aggregate/Project.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/application/dto/request/CreateReviewRequest.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/review/command/domain/aggregate/Review.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/Be154thB612LittleprinceBeApplicationTests.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/famousquotes/query/service/FamousQuotesQueryServiceImplTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/item/command/application/service/BadgeCommandServiceImplTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/item/command/application/service/ItemCommandServiceTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/item/query/service/BadgeQueryServiceTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/item/query/service/ItemQueryServiceTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/member/query/service/ExpQueryServiceTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/member/query/service/MemberQueryServiceImplTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/plan/command/application/service/LongTodoCommandServiceTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/plan/command/application/service/ProjectCommandServiceTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/plan/command/application/service/ProjectTaskCommandServiceTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/plan/command/application/service/ShortTodoCommandServiceTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/plan/query/service/LongListQueryServiceTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/plan/query/service/RateQueryServiceTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/plan/query/service/ShortListQueryServiceTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/review/command/application/service/ReviewCommandServiceTest.java
  be15-4th-b612-littleprince-be/src/test/java/littleprince/review/query/service/ReviewQueryServiceTest.java
Labels: feat

#199 Dlp 99 be 획득 경험치 입력 구현
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/scheduler/ExpScheduler.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/service/MemberCommandService.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/application/service/MemberCommandServiceImpl.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/mapper/ExpHistoryCommandMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/command/scheduler/ExpScheduler.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/member/query/mapper/ExpHistoryQueryMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/repository/ProjectRepository.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/plan/command/repository/TaskRepository.java
  be15-4th-b612-littleprince-be/src/main/resources/mappers/member/ExpHistoryCommandMapper.xml
  be15-4th-b612-littleprince-be/src/main/resources/mappers/member/ExpHistoryQueryMapper.xml
Labels: feat

#213 fix: 마이페이지 클릭 시 호버 안되는 오류 수정
  be14-4th-b612-littleprince-fe/src/components/layout/SideBar.vue
Labels: fix

#217 feat: open weather api 연결하여 날씨로 할 일 추천
  be15-4th-b612-littleprince-be/src/main/java/littleprince/config/OpenWeatherConfig.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/weather/query/controller/WeatherQueryController.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/weather/query/dto/WeatherDTO.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/weather/query/dto/response/WeatherRecommendationResponse.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/weather/query/dto/response/WeatherResponse.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/weather/query/exception/WeatherErrorCode.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/weather/query/mapper/WeatherMapper.java
  be15-4th-b612-littleprince-be/src/main/java/littleprince/weather/query/service/WeatherQueryService.java
  be15-4th-b612-littleprince-be/src/main/resources/application.yml
  be15-4th-b612-littleprince-be/src/main/resources/mappers/weather/WeatherMapper.xml
Labels: feat

#220 Dlp 108 fe 오늘의 할 일 api 연동
  be14-4th-b612-littleprince-fe/src/features/calendar/api.js
  be14-4th-b612-littleprince-fe/src/features/main/components/MainIconItem.vue
Labels: feat, fix
